application: prdictapi
version: 0-2-5
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /static-%BUILD%
  static_dir: static-%BUILD%
  expiration: "365d"

- url : /robots.txt
  static_files: static-%BUILD%/robots.txt
  upload: static-%BUILD%/robots.txt

- url: /google76098d9def48f10d.html
  static_files: static-%BUILD%/google76098d9def48f10d.html
  upload: static-%BUILD%/google76098d9def48f10d.html

- url: /gae_mini_profiler/static
  static_dir: gae_mini_profiler/static

- url: /gae_mini_profiler/.*
  script: gae_mini_profiler/main.py
  
- url: /dev/populate
  login: admin
  script: prdictapi.py

- url: /task/.*
  login: admin
  script: prdicttask.py

- url: /.*
  script: prdictapi.py

inbound_services:
  - channel_presence
